### ISSUE TITLE
Add Board "Adafruit ESP32-S2 Feather with BME280 Sensor - STEMMA QT - 4MB Flash + 2 MB PSRAM"

### ISSUE THREAD

**Issue by cTurtle98** [platformio/platform-espressif32#981]
this board does not have a definition. I am unable to flash it with esphome

https://www.adafruit.com/product/5303

**Comment by cTurtle98** [comment]
using this
```
esp32:
  board: featheresp32-s2
  variant: esp32s2
  framework:
    type: arduino
```
appears to be working for this board right now
